### ISSUE TITLE
[ENHANCEMENT] Get FLEET_ENROLLMENT_TOKEN

### ISSUE THREAD

**Issue by PfiatDe** [peasead/elastic-container#39]
First this is really a wonderful project. Thanks for it!

**Is your feature request related to a problem? Please describe.**
When automating the deployment it is always a small hassle to get the enrollment token for the fleet, as it involves connecting the UI.

**Describe the solution you'd like**
There would be serveral solutions:
a) A way to get it via the API. I did not find the correct APIs to talk to to get them. This seems only to work for Cloud?
https://www.elastic.co/guide/en/cloud-enterprise/current/get-enrollment-tokens.html

b) Define the FLEET_ENROLLMENT_TOKEN via an ENV Variable in the docker-compose / .env
As this is only a test system this might be fine

c) Get it somewhere else and log or print it during the setup / start phase

I am talking about this Token:
![image](https://github.com/peasead/elastic-container/assets/47333109/263a772a-345d-4b58-999b-43f2be6bf710)

**Comment by peasead** [comment]
Thanks for checking out the project, @PfiatDe 

Because there are a lot of nuance in what policy someone might want and for what OS, I think it'd be best to not build that into the script, but provide it in the README as a way to do it. I'll do that and I think it's a great idea.

I haven't tried it yet, but I _think_ this will work that way? I'm going to try it in a bit.

```bash
curl -k -u elastic --request GET \
  --url 'https://kibana:5601/api/fleet/enrollment_api_keys' \
  --header 'Content-Type: application/json' \
  --header 'kbn-xsrf: xx'
```

Ref: https://www.elastic.co/guide/en/fleet/current/fleet-api-docs.html#get-enrollment-token-api

**Comment by PfiatDe** [comment]
This is working great, thanks!
Created a PR with some documentation. Feel free to edit or adjust as you want.
https://github.com/peasead/elastic-container/pull/40

Thanks for keeping this project up :)

**Comment by peasead** [comment]
#40 merged. 

Thanks for the contribution!
